spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone_be
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      converters:
        preferred-json-mapper: jackson
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000