spring:
  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:36009/railway
    username: root
    password: BHdSzHraIHMnOgnLYuaDymxCyaZAZhoR
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  sql:
    init:
      mode: never

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
